pipeline {
    agent any
    tools { maven "maven" }
    stages {
        stage('SCM') {
            steps {
                git branch: 'main', url: 'https://github.com/Santhosh-P-2005/DevOps-Day-3.git'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t santhosh9405/webapp1 .'
                }
            }
        }
        stage('Push to Docker Hub') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker_cred', toolName: 'docker', url: 'https://index.docker.io/v1/') {
                        sh 'docker push santhosh9405/webapp1'
                    }
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    
                    withKubeConfig(caCertificate: '', clusterName: 'minikube', contextName: 'minikube', credentialsId: 'new_kub_config', namespace: '', restrictKubeConfigAccess: false, serverUrl: 'https://192.168.49.2:8443') {
         sh 'kubectl apply -f deployment.yml --validate=false'
}
                }
            }
        }
    }
}
