# Use the official Nginx image
FROM nginx:latest

# Copy custom configuration file (if needed)
# COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 8060

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]


